
[golang]
max_cpu_num=3

[consul]
host="127.0.0.1:8500"
key=""

[service]
name="simple"
id="kits_simple_8080"
host=":8080"
reportable=true
report_host="ip_of_interface(eth0)"
tags=["master","v1.2.3"]
error_prefix="kits_simple_"
handle_pprof = true
handle_pprof_prefix="/abcdefg"

[mongo]
url="amqp://root:abc123@127.0.0.1:27017/admin"

[redis]
host="127.0.0.1"
password="abc123"
db=1

[application]
sync_interval=10s
max_symbols=1024
report_data_config="kv_of_consul(kits.simple.report_data)"


