
[base]
max_cpu_num=3

[service]
name="simple-service2"
id="kits_simple_8080"
host=":8080"
reportable=true
report_host="ip_of_interface(eth0)"
tags=["master","v0.2.1"]
error_prefix="kits_simple_"
handle_pprof = true
handle_pprof_prefix="/abcdefg"

[mongo]
url="amqp://root:abc123@127.0.0.1:27017/admin"

[redis]
host="kv_of_consul(kits.sample.redis.host)"
password="abc123"
db=1

[application]
sync_interval=10s
max_symbols=1024
report_data_config="kv_of_consul(kits.simple.report_data)"

[zipkin]
host="kv_of_consul(common.zipkin.host)"

[discovery]
enable_consul = true
consul_host="127.0.0.1:8500"

enable_static = true
static_services=[
    "auth_service 127.0.0.1:10630",
    "product_service 127.0.0.1:1923 127.0.0.1:2023"
]



